"""Add created_at and updated_at columns to User

Revision ID: 05c8df8e6977
Revises: 
Create Date: 2024-11-06 11:43:03.359663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c8df8e6977'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_providers_id', table_name='providers')
    op.drop_index('ix_providers_name', table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_medications_id', table_name='medications')
    op.drop_table('medications')
    op.drop_index('ix_patients_id', table_name='patients')
    op.drop_index('ix_patients_name', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patients_name', 'patients', ['name'], unique=False)
    op.create_index('ix_patients_id', 'patients', ['id'], unique=False)
    op.create_table('medications',
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('dosage', sa.VARCHAR(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medications_id', 'medications', ['id'], unique=False)
    op.create_table('providers',
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('specialty', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_providers_name', 'providers', ['name'], unique=False)
    op.create_index('ix_providers_id', 'providers', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('provider_id', sa.INTEGER(), nullable=True),
    sa.Column('appointment_date_time', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_id', 'appointments', ['id'], unique=False)
    # ### end Alembic commands ###
