name: Build and deploy Python app to Azure Web App - health-info-sys-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, etc.)

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" "*.venv*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1816C8954EF04F66BAA817A1A82F8A8C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3BE8BEEBA9B04E3FBA133AB959CAAB0A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_710FB75825BF45FEB37EBCB342352661 }}

      - name: Set the startup command for Azure
        run: |
          az webapp config set --resource-group myResourceGroup --name health-info-sys-api --startup-file "uvicorn app.main:app --host 0.0.0.0 --port 80"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'health-info-sys-api'
          slot-name: 'Production'
